version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  dev:
    desc: Start development server
    cmds:
      - pnpm run dev

  build:
    desc: Build for production
    cmds:
      - pnpm run build

  start:
    desc: Start production server
    cmds:
      - pnpm run start

  lint:
    desc: Run ESLint
    cmds:
      - pnpm run lint

  install:
    desc: Install dependencies
    cmds:
      - pnpm install

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf .next
      - rm -rf node_modules/.cache
